### ISSUE TITLE
Integration with PagerDuty

### ISSUE THREAD

**Issue by vinermax** [sassoftware/viya4-monitoring-kubernetes#105]
A customer has asked if we can integrate with PagerDuty, is this something that we can support in the future?

**Comment by BryanEllington** [comment]
Alertmanager includes PagerDuty support:
https://www.pagerduty.com/docs/guides/prometheus-integration-guide/

There are several resources on how to set up PagerDuty with Alertmanager, but here's a Grafana blog:
https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/

As for integrating with the helm chart, check out https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L150 to see what. you might add to your `$USER_DIR/monitoring/user-values-prom-operator.yaml` file.

We have plans for a documented sample that will include some more explanation, doc, and example response files for alert integrations. That's not happening in the short term, but it's on our radar.

**Comment by gsmith-sas** [comment]
We should also point out that if you (or the customer) want to prototype/implement something before we do, please consider submitting it as a Pull Request so we can share it with the community.

**Comment by vinermax** [comment]
This is great, thank you.
