### ISSUE TITLE
Deploying rules in AWS

### ISSUE THREAD

**Issue by devopsasadm** [sassoftware/viya4-monitoring-kubernetes#110]
Hi,

INFO Helm client version: 3.5.4
INFO Kubernetes client version: v1.18.19
INFO Kubernetes server version: v1.18.16-eks-7737de

We ran into this error with webhook while deploying monitoring on an EKS cluster.  The error occurred when apply this rule: rules-sas-launcher-job.yaml

INFO Adding Prometheus recording rules...
Error from server (InternalError): error when creating "monitoring/rules/viya/rules-sas-launcher-job.yaml": Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://v4m-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s: context deadline exceeded

I modified the deploy_monitoring_cluster.sh and commented out the this section and the monitoring installed correctly with exception of applying the rules.

        # Rules
        log_info "Adding Prometheus recording rules..."
        for f in monitoring/rules/viya/rules-*.yaml; do
          kubectl apply -n $MON_NS -f $f
        done

I ran into a similar issue with webhooks in AWS but it didn't seem to like any modifications I made to (  --set webhook.hostNetwork=true,webhook.securePort=<some port>) during the helm install of prometheus.  Those 2 settings have had to set in another helm install with a webhook issue and it fixed this issue in the past.   Also, checked to see if there were any lingering CRDs or validatingwebhookconfigurations or MutatingWebhookConfiguration.   

Thanks in advance

**Comment by gsmith-sas** [comment]
@devopsasadm Thank you for reporting this.  Given the age of this issue, I'm going to close it as "stale".  We (now) regularly deploy onto both EKS and AWS clusters and have not seen this problem.  Please open a new issue if you are still seeing this issue.
