### ISSUE TITLE
Dashboard for Viya 4 Open Distro Elasticsearch (as opposed to Viya 4 logging Elasticsearch)

### ISSUE THREAD

**Issue by pilyk** [sassoftware/viya4-monitoring-kubernetes#151]
After installing Viya 4 Monitoring and Logging, I noticed that the dashboard for Elasticsearch is for the Viya 4 logging.  However, I would like to see the dashboard for Viya 4 Open Distro for Elasticsearch as well.  

I do see the ServiceMonitor for sas-elasticsearch.

Appreciate any recommendation how to surface the metrics in Grafana for the Viya 4 Open Distro for Elasticsearch.  Maybe make a copy of the Viya 4 logging Elasticsearch dashboard and modify?  However, I didn't see the necessary metrics.  Must be missing something obvious.

Thanks.

**Comment by gsmith-sas** [comment]
Hello @pilyk,

  Thank you for taking the time to report this issue.  
  Deploying the metric monitoring is a two-part process: first, you deploy the cluster-level monitoring components (using the deploy_monitoring_cluster.sh script); and, then you need to instrument each of the Viya deployments (e.g. deploy additional components into each of the Viya namespaces) running on the cluster (by running the deploy_monitoring_viya.sh script for each Viya deployment/namespace).  If you haven't done the second step, none of the Viya-specific dashboards in Grafana will show any data.  Missing that step in the monitoring/readme.md file is one of the most common source of problems.

  However, in this particular case, even if you do that, you probably won't be able to see metrics for the Open Distro for Elasticsearch instance within your Viya deployment.  Coincidentally, earlier today, one of our coworkers noticed this same problem.  We are currrentally investigating the cause and hope to determine the best way to fix quickly.  

  We will update this ticket as progress on this is made.

**Comment by pilyk** [comment]
Thanks for the response.

Please note that I have done the two-part process and have some of the Viya-specific dashboards.  I also noticed that we don't have any deployment operator even though the ServiceMonitor is registered.  Will that also be looked at?

Thanks again.

**Comment by gsmith-sas** [comment]
@pilyk  Please open a separate issue for the missing sas-deployment-operator metrics so we can track each issue separately.  Thank you.  We're still investigating both issues but they one or both may require changes on the Viya side rather than on the monitoring side.  We'll post updates to the appropriate issues as we figure things out.

**Comment by gsmith-sas** [comment]
@pilyk   I have spoken to the development team responsible for the instance of the Open Distro for Elasticsearch used within Viya.  Evidently, the team stopped deploying the metric exporter piece while they work through issues related to some TLS configurations.  The metric exporter is the component that makes the metrics available to Prometheus and, thus, to our monitoring processes.  The team hope to make metrics available again in the future.  I'll leave this issue "open" until we have this metrics available again.  Still looking into the sas-deployment-operator issue.

**Comment by pilyk** [comment]
Thanks for the update on the Open Distro for Elasticsearch.  Hopefully, we will see the metrics soon.

**Comment by gsmith-sas** [comment]
The developers responsible for the Open Distro for Elasticsearch instance within a SAS Viya deployment have informed me that they have just completed their work to deploy the Elasticsearch Exporter component as part of a Viya deployment.  This will make metrics about the health and performance of that instance of Elasticsearch available in Grafana once again.  

The changes should start appearing in publicly available images on the Viya monthly/stable cadence track as part of the SAS Viya 2021.2.1 release due out, I believe, next week.  Unfortunately, this work did not make it into the SAS Viya 2021.2 LTS release due out around the same time.  However, it should be there for the next LTS release expected early next year.
