### ISSUE TITLE
Missing sas-deployment-operator metrics

### ISSUE THREAD

**Issue by pilyk** [sassoftware/viya4-monitoring-kubernetes#152]
As per https://github.com/sassoftware/viya4-monitoring-kubernetes/issues/151, creating another issue to track missing deployment operator metrics.

Thanks.

**Comment by gsmith-sas** [comment]
Thank you @pilyk ... We will update this issue as we identify the root cause and potential solutions.

**Comment by gsmith-sas** [comment]
The SAS Deployment Operator developers removed the metrics endpoint from which surfaced metrics to Prometheus.  There are on-going discussions about if/how the SAS Deployment Operator should surface metrics.  I will update this issue when the plan has been finalized.

**Comment by gsmith-sas** [comment]
After further discussion, we determined metrics are actually being surfaced by the SAS Deployment Operator just not on the port our project was expecting.  We will update our service monitor definition to fix this is an upcoming release.

**Comment by gsmith-sas** [comment]
@pilyk Pull Request #172 was pushed earlier today and fixed this issue.  This fix will be available in our **stable** branch as part of our next release, due out in mid-October.  If you are especially eager for this fix, it is available now in our **master** branch.  However, please be aware that our **master** branch is our live development branch and, therefore, is updated very frequently and contains other fixes, changes and other work in progress.  The **stable** branch is updated less frequently, generally once a month, and contains a more cohesive, more thoroughly tested, set of changes.
