### ISSUE TITLE
Grafana's SAS Dashboards - no data

### ISSUE THREAD

**Issue by warrior88** [sassoftware/viya4-monitoring-kubernetes#156]
Hi,
After installing viya4 monitoring and logging using viya4-deployment tool, the Kubernetes dashboards are showing nice statistics and graphs in Grafana, however, all the SAS dashboards are not picking up any data. The Viya version is LTS 2021.1.

Prometheus' query text box is also not able to find any matching metric for "cas_" and "cas_nodes".
Would there be any post-installation step that I am missing?

<img width="879" alt="Grafana" src="https://user-images.githubusercontent.com/53848732/130356408-f07fab9d-112b-41dc-9c45-f16bd5ed3390.png">

**Comment by BryanEllington** [comment]
You can run monitoring/bin/deploy_monitoring_viya.sh to enable monitoring for each Viya namespace in the cluster.

I thought the viya4-deployment project had options for enabling the Viya namespace for monitoring, but that might be a more recent change.

**Comment by gsmith-sas** [comment]
@warrior88 The [Viya 4 Deployment](https://github.com/sassoftware/viya4-deployment) project runs the `deploy_monitoring_viya.sh` @BryanEllington  mentioned as the task "**_viya-monitoring_**".  So, if you include that task/tag the list of deployment tasks when using the Viya 4 Deployment project, it should deploy the necessary instrumentation needed to get metrics flowing from your Viya deployment and into Prometheus/Grafana.
