### ISSUE TITLE
TLS kibana 502 bad gateway

### ISSUE THREAD

**Issue by ricgatti** [sassoftware/viya4-monitoring-kubernetes#181]
Hello, I'm deploying the logging part with TLS enable.

I have made the customization in my yaml file as follow

```
kibana:
  extraEnvs:
  - name: SERVER_BASEPATH
    value: /kibana
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: username
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: password
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite (?i)/kibana/(.*) /$1 break;
        rewrite (?i)/kibana$ / break;
      nginx.ingress.kubernetes.io/rewrite-target: /kibana
    enabled: true
    hosts:
    - hostname/kibana
    tls:
      - secretName: kibana-ingress-tls-secret
        hosts:
          - hotsname
```

When I try to acces the web page I get 502 bad gateway with the following error in nginx ingress log

```
2021/09/28 12:26:38 [error] 5574#5574: *415692 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 192.168.16.4, server: hosthame, request: "GET /kibana HTTP/2.0", upstream: "https://192.168.16.89:5601/", host: "hosthame"
2021/09/28 12:26:38 [error] 5574#5574: *415692 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 192.168.16.4, server: hosthame, request: "GET /kibana HTTP/2.0", upstream: "https://192.168.16.89:5601/", host: "hosthame"
2021/09/28 12:26:38 [error] 5574#5574: *415692 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 192.168.16.4, server: hosthame, request: "GET /kibana HTTP/2.0", upstream: "https://192.168.16.89:5601/", host: "hosthame"
192.168.16.4 - admin [28/Sep/2021:12:26:38 +0000] "GET /kibana HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" 25 0.003 [logging-v4m-es-kibana-svc-443] [] 192.168.16.89:5601, 192.168.16.89:5601, 192.168.16.89:5601 0, 0, 0 0.004, 0.000, 0.000 502, 502, 502 df84a71026cdc776daf36c9cc15789b8
```

Any suggestion where the error can be?

Thanks

**Comment by gsmith-sas** [comment]
Hello,

  Ingress configuration can be tricky and I'm no expert, so I'm not sure I'll be able to solve this.  However, let me make a few suggestions/comments:

- I noticed a typo in the yaml file you shared.  On the last line, you identify the "host" as "ho**ts**name"; I suspect that should have been "ho**st**name" (you swapped the "s" and "t" in the middle).  But I'm not sure if that was the actual value in your yaml file or just a dummy value you used to avoid revealing your actual host name.  If it is an actual value, correct the typo and see if that fixes the problem.
- I notice the server/host is identified as "host**h**ame" in the nginx ingress log messages you shared.  Again, I don't know if that was just a typo somewhere in the actual configuration or a mistake in a global change you made to hide the actual host before posting the log messages.  If it is the former, check your configuration for the typo (I don't see that typo in your yaml).
- You did not include the URL you are using to access Kibana.  Are you specifying HTTP or HTTPS as the protocol?  In either case, have you tried specifying the other value?

  I'm sorry I can't be more helpful.  Please let us know how things go.

**Comment by ricgatti** [comment]
Hello,

The value hotsname, yeah is  wrong typo but it's only a dummy value.
When I try to access I specift https://hostname/kibana

**Comment by gsmith-sas** [comment]
Hello again,
Another user recently ran into a similar problem and we realized they had failed to create all of the necessary TLS certificates.  We generate some of the certificates for you but not all.  Have you obtained a set of TLS certificates and saved them as the Kubernetes secret _kibana-ingress-tls-secret_ (within the logging namespace)?  If you have NOT populated that secret with a valid set of TLS certs, things won't work.  There are instructions within the [repo](https://github.com/sassoftware/viya4-monitoring-kubernetes/tree/master/samples/tls/logging#specifying-tls-for-ingress) that describe how to create the secret once you have obtained a TLS cert.

**Comment by ricgatti** [comment]
Hello,

With `LOG_KB_TLS_ENABLE` set to `true` it deploy correctly and I can access the web page with HTTPS.
The TLS certificate as been created correctly using my cluster issuer.

I thinks we can close the issue now thanks.
