### ISSUE TITLE
Grafana Dashboards not working

### ISSUE THREAD

**Issue by wweghe** [sassoftware/viya4-monitoring-kubernetes#184]
Hi ,

I tried a couple of time to deploy the Viya 4 monitoring framework, during installation of the standard scripts I see no errors, however, when I try to access one the of the standard dashboards I get this error
![grafana](https://user-images.githubusercontent.com/26930349/135825769-17aee2d1-422b-478c-b95a-8ff2ed2a35ff.PNG)
and nothing is displayed 
Also when I try to access some of the Viya 4 specific dashboards I get similar errors : 
![grafana2](https://user-images.githubusercontent.com/26930349/135826960-0977af32-5c8c-45f3-9e6f-276ffcbb148d.PNG)
![grafana3](https://user-images.githubusercontent.com/26930349/135826965-610cbe88-3bba-4d18-84df-27edaf051d0f.PNG)

Anything I'm missing ?

**Comment by BryanEllington** [comment]
Hello,

When you get a 'bad gateway' message in Grafana, the most likely problem is that Prometheus is not running or not accessible. Check the status of the pods in the monitoring namespace and look for problems.

**Comment by wweghe** [comment]
Hi ,
I removed and re-enabled a couple of times, and it seems working now.
Don't know what changed...
Closing for now

**Comment by wweghe** [comment]
Thanks
