### ISSUE TITLE
fluent bit pod failed with " cannot open database" error

### ISSUE THREAD

**Issue by eric80116** [sassoftware/viya4-monitoring-kubernetes#216]
After deploy deploy_logging_open.sh and got the error below

[2021/11/01 08:27:26] [error] [sqldb] cannot open database /var/log/sas_viya_flb.db
[2021/11/01 08:27:26] [error] [input:tail:tail.0] could not open/create database
[2021/11/01 08:27:26] [error] Failed initialize input tail.0
[2021/11/01 08:27:26] [error] [lib] backend failed

Any idea?

**Comment by gsmith-sas** [comment]
@eric80116   Sorry to hear you ran into a problem deploying things.  Fluent Bit is the log collection component of our log monitoring solution.  It is tasked with watching all of the pod/container logs, collecting messages and sending them on to the Elasticsearch back-end.  It uses a database to keep track of where it is within each pod/container log file.  That database is stored in files in the /var/log directory on each node in the cluster.  The error message you encountered indicates that it was unable to create/open that database file.  

That is a problem we have not seen before.  We have tested on a number of cloud providers and Kubernetes versions without problems.  Can you provide additional information about your environment (i.e. cloud provider, K8s versions, special security set-ups, etc.)?  We require that the deployment scripts are run by a user with full Kubernetes admin access; are you running with  a more limited set of permissions?

**Comment by eric80116** [comment]
Hi @gsmith-sas ,
I ran the script with root permission on following environment 
cloud provider: AWS
K8s version: v1.21.2
security set-ups: The security group set for all traffic type, all protocol and all port
for now, we can only see the logs by 'kubectl logs [fluent-bit pod]' and 'kubetl describe pod [fluent-bit pod]', is there any configuration can get more detail logs? 
Thanks

**Comment by gsmith-sas** [comment]
Hi @eric80116, thank you for the additional information.  Unfortunately, we're still not sure why you are experiencing problems.
  Are you planning on deploying SAS Viya 4 onto this cluster?  If so, we generally prepare our AWS clusters using a sibling project, [SAS Viya 4 Infrastructure as Code (IaC) for Amazon Web Services (AWS)](https://github.com/sassoftware/viya4-iac-aws).  Was your cluster created using that project?  If not, you may want to look at that project and see if it will work for your purposes.
