### ISSUE TITLE
Instructions for applying Viya ServiceMonitors

### ISSUE THREAD

**Issue by seanankenbruck** [sassoftware/viya4-monitoring-kubernetes#228]
I have recently deployed the monitoring components into a new Viya deployment on EKS. However, prometheus and grafana are not displaying any information and tech support directed me to ask this project for further instructions or resources. I do see the documentation regarding ServiceMonitors [here](https://go.documentation.sas.com/doc/en/itopscdc/v_018/itopsmonitoring/p1o5vd767ech3an10c7jx770hkm5.htm).  

However, there is not a specific set of instructions for deployment. Is it as simple as applying the manifest, or are there additional steps? For example: 

_kubectl apply -f viya/serviceMonitor-sas-cas-operator.yaml -n monitoring_

**Comment by BryanEllington** [comment]
Hi there,

The SAS Viya ServiceMonitors are deployed when you enable the Viya namespace for monitoring. This is a specific step that needs to be done for each Viya namespace in the cluster.

See https://github.com/sassoftware/viya4-monitoring-kubernetes/tree/stable/monitoring#deploy-sas-viya-monitoring-components for details.

**Comment by seanankenbruck** [comment]
Hi Bryan, 

We have deployed the components to monitor the cluster (deploy_monitoring_cluster.sh) and Viya (deploy_monitoring_viya.sh), but Grafana does not show any data. Here is what the SAS Cas Overview dashboard looks like: 

![image](https://user-images.githubusercontent.com/7320213/142464739-de353ec6-4325-45c5-89c3-025bdcbf5127.png)

**Comment by seanankenbruck** [comment]
For additional context, I only configured the user-values-prom-path.yaml file in the samples/ingress location of this project prior to deployment. Are there additional files that we need to pull from one of the other sample directories?

**Comment by BryanEllington** [comment]
Changing any files in samples won't have an effect. You can read [here](https://github.com/sassoftware/viya4-monitoring-kubernetes/tree/master/monitoring#mon_custom) about setting a `USER_DIR` and customization.

The first thing to check is if Grafana can talk to Prometheus and if cluster monitoring is working. Look at the 'Kubernetes Cluster' dashboard in Grafana. If that has data, then it's just an issue of properly enabling monitoring of the SAS Viya deployment.

To troubleshoot monitoring a SAS Viya Deployment, you can check Prometheus - Go to the `Status` menu, then click `Service Discovery`. Look for various PodMonitor/[namespace]/sas-* or ServiceMonitor/[namespace]/sas-* entries and see if any targets are found. If so, that means the deployment is being properly watched. Assuming there are targets, you can check `Status` -> `Targets` to see if there are any errors monitoring the SAS components. If there are no targets or you don't see the 'sas-*' entries under Service Discovery, then you probably need to run `monitoring/bin/deploy_monitoring_viya.sh` again and make sure you set `VIYA_NS` to the namespace containing your Viya deployment. For example:
`VIYA_NS=my-viya-namespace monitoring/bin/deploy_monitoring_viya.sh`

I hope this helps. Let me know how it goes.

**Comment by gsmith-sas** [comment]
Assuming no news is good news here.  Closing this issue.
