### ISSUE TITLE
Integration of Viya4 Monitoring with GCP Cloud Monitoring

### ISSUE THREAD

**Issue by alessio4tech** [sassoftware/viya4-monitoring-kubernetes#250]
GCP recommends using workload metrics instead of the sidecar container for integration with its Cloud Logging and Monitoring framework. See https://cloud.google.com/stackdriver/docs/solutions/gke/managing-metrics#workload-metrics for more details. Our deployment descriptors from under https://github.com/sassoftware/viya4-monitoring-kubernetes/tree/9ead02a1e46cd34842005d2b903d3d839081122d/monitoring/monitors/viya are not readily compatible with GCP. Could you please embrace the new recommended way of integrating with Cloud Monitoring & Logging.

**Comment by BryanEllington** [comment]
Hi there,

Google Workload Metrics is currently still [in preview](https://cloud.google.com/stackdriver/docs/solutions/gke/installing#available-metrics), so it's still a bit early. We do have a story in the backlog to add a sample that documents the use of Workload Metrics to monitor SAS Viya services.

It doesn't look too bad - Google decided to create their own PodMonitor custom resource modeled off of the [PodMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#podmonitor) defined by the Prometheus Operator.

I don't have a timeline for you, but it's on the radar. We're also doing a refresh of our support for the native monitoring solutions of all of the supported cloud providers.
