### ISSUE TITLE
Grafana not accessible through its ingress

### ISSUE THREAD

**Issue by sasbxs** [sassoftware/viya4-monitoring-kubernetes#318]
In the sample file: monitoring/samples/azure-deployment there are ingresses set up for prometheus, alertmanager and grafana.  Using the sample file (changing hostnames as directed) I could not access grafana from its ingress address (but I could access prometheus and alertmanager).  What I found is that the section of this file pertaining to grafana is missing the following two lines that appear in both the prometheus and alertmanager sections:

    annotations:
      kubernetes.io/ingress.class: nginx

Once I added those two lines to the grafana section and re-deployed I am able to access the grafana ingress.   If I'm missing something and have approached this incorrectly, please let me know -- but I think this could be an issue.

**Comment by gsmith-sas** [comment]
SASBXS:  Thanks for reporting this.  I believe you have correctly identified the issue and the right solution.  I will add an item on our To Do list to update our sample.
