### ISSUE TITLE
shows sas-esp-operator-metrics target as down even though working

### ISSUE THREAD

**Issue by michburger** [sassoftware/viya4-monitoring-kubernetes#325]
Dear sassoftware,
we've installed the viya4 monitoring components and find these targets down even though the PODs are running fine:

serviceMonitor/viya4/sas-esp-operator-metrics/0 (0/1 up)
serviceMonitor/viya4/sas-esp-operator-metrics/1 (0/1 up)

in the details of the targets' configuration, the URL differs from the POD annotations.

The endpoint prometheus uses:
http://10.244.0.167:8383/metrics
http://10.244.0.167:8686/metrics

The endpoint according to the POD's annotations
 annotations:
    prometheus.io/path: /internal/metrics
    prometheus.io/port: '8383'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'

 annotations:
    prometheus.io/path: /internal/metrics
    prometheus.io/port: '8686'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'

Is there a way to correct and update the URL path setting for monitoring?

**Comment by gsmith-sas** [comment]
@michburger   I'm working with the ESP dev team to sort out what needs to be done.  In the meantime, you can probably manually update the annotations on those pods to see if the metrics start flowing.  Your manual annotation changes won't persist if the pods restart, but it might be an easy way to see some metrics.  I'll report back when we've sorted things out further.

**Comment by michburger** [comment]
Dear gsmith-sas, changing the annotations is fine with me. How can I restart the monitoring system so that the annotations are getting effective?

**Comment by myuser-git** [comment]
@michburger, the binaries for the ESP monitoring stack on GitHub have been refreshed. The new version works with Grafana 8.1. To further help you, I would need more information on your environment (i.e. is your environment hosted on the cloud). Also, to clarify things, the ESP monitoring stack is not currently integrated with the Viya4 monitoring stack. Should you need to open an issue, please refer to [this](https://github.com/sassoftware/iot-kubernetes-monitoring-esp) page.

**Comment by gsmith-sas** [comment]
Closing this issue.  As @myuser-git mentioned above, the ESP monitoring stack is currently maintained as part of a separate GitHub project: https://github.com/sassoftware/iot-kubernetes-monitoring-esp.
