### ISSUE TITLE
Upgrade : Unable to access Kibana URL after upgrade.

### ISSUE THREAD

**Issue by sangram23** [sassoftware/viya4-monitoring-kubernetes#338]
Hi Team, 

Our Kibana url before upgrade was https://Client -viya4-Box.xxxxxxxx.xxxxxxx.corp/kibana and after upgrade "ip-x-x-x-x.ec2.internal:" instance is coming . Unable to access Kibana right now

Note : Changed the the above URL name security purpose

NOTES:
Viya Monitoring for Kubernetes 1.1.8-SNAPSHOT is installed

^[[1;37m^[[44m**Elasticsearch/Kibana Access Controls**                                       ^[[0m
^[[1;37m^[[44mAssign users the back-end role of [V4MCLUSTER_ADMIN_kibana_users] to           ^[[0m
^[[1;37m^[[44mgrant them access to Kibana and log messages from                              ^[[0m
^[[1;37m^[[44mALL tenants and ALL namespaces                                                 ^[[0m
^[[1;37m^[[44m                                                                               ^[[0m
^[[1;37m^[[44m**Accessing the monitoring applications**                                      ^[[0m
^[[1;37m^[[44m                                                                               ^[[0m
^[[1;37m^[[44mYou can access KIBANA via the following URL:                                   ^[[0m
^[[1;37m^[[44mhttp://ip-x-x-x-x.ec2.internal:31033                                      ^[[0m
^[[1;37m^[[44m                                                                               ^[[0m
^[[1;37m^[[44mIt was not possible to determine the URL needed to access ELASTICSEARCH        ^[[0m
^[[1;37m^[[44m                                                                               ^[[0m
^[[1;37m^[[44mNote: These URLs may be incorrect if your ingress and/or other network         ^[[0m
^[[1;37m^[[44mconfiguration includes options this script does not handle.                    ^[[0m
^[[1;37m^[[44m                                                                               ^[[0m

^[[1;37m^[[44mThe deployment of logging components has completed [Tue Apr 26 12:12:55 UTC 2022]^[[0m

^[[1;37mDEBUG ^[[0;37mDeleted temporary directory: [/tmp/sas.mon.Ff1P1CSh]^[[0m

******************************************

upgrade process 

1)- Download latest Repo
2)- export $USER_DIR= path --- Custom  files  mention below

user.env
user-values-elasticsearch-path.yaml -- Has custom URL

3)- Run ./logging/bin/deploy_logging_open.sh 

********************************************

kibana:
  extraEnvs:
  # Needed for path-based ingress
  - name: SERVER_BASEPATH
    value: /kibana
  # Username & password need to be set here since helm *replaces* array values
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: username
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: password
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite (?i)/kibana/(.*) /$1 break;
        rewrite (?i)/kibana$ / break;
      nginx.ingress.kubernetes.io/rewrite-target: /kibana
    enabled: true
    # ingressClassName is not currently supported by the Open Distro helm chart
    # ingressClassName: nginx
    path: /kibana
    pathType: Prefix
    hosts:
    - Client -viya4-Box.xxxxxxxx.xxxxxxx.corp

**Comment by gsmith-sas** [comment]
@sangram23   I noticed you are deploying from the "master" branch of our repo.  We would recommend you deploy from the "stable" branch.  Since we are actively pushing changes each day to "master", it is generally a better idea to use the "stable" branch which is only updated monthly. 

I believe the problem is caused by an incorrect file name.  The `user-values-elasticsearch-path.yaml` file should be called `user-values-elasticsearch.yaml`.  In some earlier versions of our project, the file was called `user-values-elasticsearch-path.yaml` and the instructions asked you to copy it to `user-values-elasticsearch.yaml`.  However, that was confusing, so we reorganized the files in samples/ingress and samples/tls to eliminate the need to rename the files.  I would suggest you also double-check the contents of your file with the current samples to make sure it is up-to-date.

We also often see problems with how the **USER_DIR** environment variable is defined.  The file `user-values-elasticsearch.yaml`  should be in a `logging` subdirectory under the directory the directory identified by the USER_DIR environment variable.  So, to get the directory listing for the file, you should submit a command like: `ls -l $USER_DIR/logging/user-values-elasticsearch.yaml`.  Oftentimes, people define USER_DIR to point to the logging subdirectory itself.  Please check that and confirm that your USER_DIR environment variable is pointing to the appropriate place.

Let us know how it goes.

**Comment by gsmith-sas** [comment]
@sangram23 

The fact that messages indicate that Kibana is available on port 31033 means that Kibana has been made available via a nodePort.  That generally only happens if ingress has not been configured.  

  Ah, I just saw your latest comment and is very helpful.  That output confirms your user customization directory is not structured properly.  You need to create a directory called `logging` under the `Logging_cust_files` directory and move the `user-values-elasticsearch.yaml` and `user.env` files down into that new (`logging`) sub-directory.

**Comment by sangram23** [comment]
Same issue :
echo $USER_DIR/
/home/user/new_sas4viya/viya4-monitoring-kubernetes-logging/Logging_cust_files/


ls -lrt $USER_DIR
total 4
-rw-r-----. 1 user ec2-user 2501 Dec 27 06:37 user.env
drwxr-x---. 2 user ec2-user   44 Apr 26 17:41 logging



 ls -lrt $USER_DIR/logging

total 4
-rw-r-----. 1 user user 1805 Apr 26 11:28 user-values-elasticsearch.yaml



***********************************************************

HOOKS:
MANIFEST:
---
# Source: v4m/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: v4m-logs
  labels:
    helm.sh/chart: v4m-1.1.7
    app.kubernetes.io/name: v4m
    app.kubernetes.io/instance: v4m-logs
    app.kubernetes.io/version: "1.1.7"
    app.kubernetes.io/managed-by: Helm
data: {}

NOTES:
Viya Monitoring for Kubernetes 1.1.7 is installed

**Elasticsearch/Kibana Access Controls**
Assign users the back-end role of [V4MCLUSTER_ADMIN_kibana_users] to
grant them access to Kibana and log messages from
ALL tenants and ALL namespaces

**Accessing the monitoring applications**

You can access KIBANA via the following URL:
http://ip-10-30-148-67.ec2.internal:31033

It was not possible to determine the URL needed to access ELASTICSEARCH

Note: These URLs may be incorrect if your ingress and/or other network
configuration includes options this script does not handle.


The deployment of logging components has completed [Tue Apr 26 17:47:43 UTC 2022]

DEBUG Deleted temporary directory: [/tmp/sas.mon.9arsDR2y]

**Comment by gsmith-sas** [comment]
@sangram23   Hmmm, that is very odd.  Please check the deployment log, near the top there should be a message line like the following:

`INFO: Loading user environment file: /some/path`

Please share that portion of the log message, that should help determine if your customization directory is being picked up.  

You've shared the contents of the user-values-elasticsearch.yaml file already, but I'd also like to see the contents of the user.env file as well.  Please be sure to remove any passwords, hostnames or other sensitive information.

**Comment by sangram23** [comment]
^[[1;37mDEBUG ^[[0;37mWorking directory: /home/ec2-user/new_sas4viya/viya4-monitoring-kubernetes-logging/viya4-monitoring-kubernetes-stable^[[0m
^[[1;32mINFO ^[[1;37mUser directory: /home/ec2-user/new_sas4viya/viya4-monitoring-kubernetes-logging/Logging_cust_files^[[0m
^[[1;32mINFO ^[[1;37mHelm client version: 3.4.0^[[0m
^[[1;32mINFO ^[[1;37mKubernetes client version: v1.21.2-13+d2965f0db10712^[[0m
^[[1;32mINFO ^[[1;37mKubernetes server version: v1.21.5-eks-bc4871b^[[0m
^[[1;37mDEBUG ^[[0;37mCluster admin check OK^[[0m
^[[1;37mDEBUG ^[[0;37mTemporary directory: [/tmp/sas.mon.9arsDR2y]^[[0m
^[[1;37mDEBUG ^[[0;37mlogging/common.sh (incoming): TLS_ENABLE=false^[[0m
^[[1;37mDEBUG ^[[0;37mSearch Backend set to [ODFE]^[[0m
^[[1;37mDEBUG ^[[0;37mV4M_CURRENT_VERSION_FULL=^[[0m
^[[1;37mDEBUG ^[[0;37mV4M_CURRENT_VERSION_MAJOR=^[[0m
^[[1;37mDEBUG ^[[0;37mV4M_CURRENT_VERSION_MINOR=^[[0m
^[[1;37mDEBUG ^[[0;37mV4M_CURRENT_VERSION_PATCH=^[[0m
^[[1;37mDEBUG ^[[0;37mV4M_CURRENT_STATUS=^[[0m

**Comment by sangram23** [comment]
USER-SUPPLIED VALUES:
user_dir:
  files: |
    user.env
    logging/user-values-elasticsearch.yaml

**Comment by sangram23** [comment]
# Configurable options for the logging scripts
# Use ENV_VAR=value or ENV_VAR="value"

# Global options
# --------------
# TMP_DIR=/tmp
 HELM_DEBUG=true
 LOG_DEBUG_ENABLE=true
 LOG_LEVEL_ENABLE=true
# LOG_COLOR_ENABLE=true

# The target namespace for the logging components
# LOG_NS=logging


# Component Deployment Flags
# ------------------------------
# The following flags control whether specific components
# of the log monitoring solution are deployed or not.

# deploy eventrouter? (generates log messages from K8s events)?
# See https://github.com/heptiolabs/eventrouter for details
# EVENTROUTER_ENABLE=true

# deploy Elasticsearch?
# ELASTICSEARCH_ENABLE=true

# deploy content (e.g. ingest pipelines, index mgmt policies, etc.)?
# ES_CONTENT_DEPLOY=true

# deploy exporter to make Elasticsearch performance metrics to Prometheus?
# ELASTICSEARCH_EXPORTER_ENABLED=true

# deploy Kibana content (e.g. visualizations, dashboards, etc.)?
# KIBANA_CONTENT_DEPLOY

# deploy Fluent Bit (log collector)?
# FLUENT_BIT_ENABLED=true


# Enables TLS in-cluster for Kibana
# ------------------------------
# This only affects the communication in-bound to Kibana.  If this is
# set to true and a TLS cert is not found saved as the expected
# Kubernetes secret (logging/kibana-tls-secret), the deployment script
# will attempt to use cert-manager to generate one on-the-fly.
# Note that these on-the-fly certs will likely lead to browser alerts
# warning of possible security risks when accessing Kibana.
# LOG_KB_TLS_ENABLE=false



# Kibana hostname override for Ingress and/or DNS Alias
# ------------------------------
# NODE_NAME specifies the host used by logging to communicate with Kibana
# The default is a node labeled with node-role.kubernetes.io/master
# followed by the first node returned by 'kubectl get nodes'
# If neither of those options are acceptable, perhaps because you are
# using DNS aliases and/or Ingress objects, specify the appropriate node/host name here
# NODE_NAME=mynode.example.com



# Retention Period Settings
# ------------------------------
# Number of Days to retain log messages
# LOG_RETENTION_PERIOD=3
LOG_RETENTION_PERIOD=15
# Number of Days to retain internal (log monitoring) log messages
# OPS_LOG_RETENTION_PERIOD=1
OPS_LOG_RETENTION_PERIOD=15



# ES Admin Password
# ------------------------------
# Password for the Elasticsearch/Kibana 'admin' user
# If not provided, a random password will be generated for this account
 ES_ADMIN_PASSWD=xxxxxxxxx

**Comment by gsmith-sas** [comment]
@sangram23  Hmm, all of that looks "right" so I don't really know why it still isn't working as expected.  It is possible that it could be something silly like an indentation issue within a yaml file.  

I know you are SAS Viya customer, so I'm going to ask you to open an issue with Tech Support.  That will allow you to share files privately.  Be sure to include a link to this GitHub issue when you open the track and mention that I've asked you to open the track.
