### ISSUE TITLE
No values from CAS

### ISSUE THREAD

**Issue by mauriziopinzi** [sassoftware/viya4-monitoring-kubernetes#375]
The CAS dashboard is empty, it looks like prometheus is not getting any metrics

cas_node_cpu_time_seconds

<html>
<body>

cas_node_cpu_time_seconds{cas_node="controller.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Controller", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="idle"} | NaN
-- | --
cas_node_cpu_time_seconds{cas_node="controller.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Controller", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="iowait"} | NaN
cas_node_cpu_time_seconds{cas_node="controller.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Controller", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="irq"} | NaN
cas_node_cpu_time_seconds{cas_node="controller.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Controller", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="softirq"} | NaN
cas_node_cpu_time_seconds{cas_node="controller.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Controller", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="system"} | NaN
cas_node_cpu_time_seconds{cas_node="controller.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Controller", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="user"} | NaN
cas_node_cpu_time_seconds{cas_node="worker-0.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Worker", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="idle"} | NaN
cas_node_cpu_time_seconds{cas_node="worker-0.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Worker", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="iowait"} | NaN
cas_node_cpu_time_seconds{cas_node="worker-0.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Worker", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="irq"} | NaN
cas_node_cpu_time_seconds{cas_node="worker-0.sas-cas-server-default.saslab.svc.cluster.local", cas_node_type="Worker", cas_server="cas-shared-default", container="cas", endpoint="http", instance="10.110.129.86:8777", job="sas-cas-server-default-client", namespace="saslab", pod="sas-cas-server-default-controller", service="sas-cas-server-default-client", type="softirq"}

</body>
</html>

**Comment by cumcke** [comment]
Hi,

Can you give us some more information about the issue that you're experiencing?

1. Is this a new deployment of this repository?  Have you ever been able to see CAS metrics on this dashboard?
2. Have you run both the deploy_monitoring_cluster and deploy_monitoring_viya scripts?  To confirm, can you provide me the output of the **helm ls -n <namespace>** command, where <namespace> represents the monitoring namespace where this project was deployed and the SAS Viya namespace.
3. When you load the SAS CAS Overview dashboard, do you see any errors?
4. Do any of the filters at the top of the dashboard load properly like in the screenshot below?
![image](https://user-images.githubusercontent.com/90708015/179071322-5ca8bf9e-5db8-45fc-b587-da25cd3af35d.png)

Regards,
Curtis

**Comment by mauriziopinzi** [comment]
Hi Curtis,
sorry for my late reply, I even tried to redeploy the monitoring tool with the latest github version with no luck
1) Yes this is a new deployment, actually it is a migration from azure to aws, on azure the tool was working fine
2) v4m-metrics             monitoring      1               2022-07-25 13:28:40.114761558 +0000 UTC deployed        v4m-1.2.2-SNAPSHOT              1.2.2-SNAPSHOT
v4m-prometheus-operator monitoring      1               2022-07-25 13:26:31.436165987 +0000 UTC deployed        kube-prometheus-stack-32.2.1    0.54.0
3) and 4) no error 
![image](https://user-images.githubusercontent.com/1130411/180794335-7882e853-d79b-4cea-ad7b-a6a0d96c90a3.png)
