### ISSUE TITLE
Grafana Dashboard for SPRE sessions

### ISSUE THREAD

**Issue by nachai9** [sassoftware/viya4-monitoring-kubernetes#377]
Pls let us know how to create Grafana dashboards on monitoring SPRE sessions of users.

**Comment by gsmith-sas** [comment]
@nachai9 Have a look at the two SAS Jobs dashboards in Grafana.  I believe they will show some metrics for SPRE sessions and batch SAS jobs.  We're currently looking into an issue (reported by some internal testers) with those dashboards not showing any metrics at all.  But we're not sure if that's only an issue with the most recent internal versions of SAS Viya or more widespread.  If none of the existing dashboards surface the metrics you need/want, you are, of course, able to create your own dashboards.  Refer to the Grafana documentation for information on how to do that.

You may also want to look at the [SAS Enterprise Monitoring offering](https://www.sas.com/en_us/software/enterprise-session-monitor.html) which is very much focused on user/session level monitoring.
