### ISSUE TITLE
Fatal Error: TASK [monitoring : cluster-logging - deploy]

### ISSUE THREAD

**Issue by terencet3** [sassoftware/viya4-monitoring-kubernetes#387]
Hello. I'm trying to deploy a Viya 4 environment (VDS) using [viya4-iac-aws](https://github.com/sassoftware/viya4-iac-aws) and [viya4-deployment](https://github.com/sassoftware/viya4-deployment/) github tools. I've encountered an error during the TASK [monitoring : cluster-logging - deploy] step and I've included the error message below. Oddly enough, I can't find any specific error to check up on besides "non-zero return code".

It seems the failure is happening when running the deploy_logging.sh script.

Would appreciate any advice if someone has encountered a similar error before,

fatal: [
  localhost
]: FAILED!=>{
  "changed": true,
  "cmd": [
    "/tmp/ansible._sw983lx/viya4-monitoring-kubernetes/logging/bin/deploy_logging.sh"
  ],
  "delta": "0:03:15.828231",
  "end": "2022-08-04 10:40:22.777705",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2022-08-04 10:37:06.949474",
  "stderr": "",
  "stderr_lines": [
    
  ],
  "stdout": "INFO User directory: /tmp/ansible._sw983lx\nINFO Helm client version: 3.9.2\nINFO Kubernetes client version: v1.22.12\nINFO Kubernetes server version: v1.22.11-eks-18ef993\n\nDeploying logging components to the [logging] namespace [Thursday, 04 August, 2022 10:37:08 AM PST]\n\nINFO Deploying Event Router ...\nserviceaccount/eventrouter unchanged\nclusterrole.rbac.authorization.k8s.io/eventrouter unchanged\nclusterrolebinding.rbac.authorization.k8s.io/eventrouter unchanged\nconfigmap/eventrouter-cm unchanged\ndeployment.apps/eventrouter unchanged\nINFO Event Router has been deployed\n\n\n\"opensearch\" already exists with the same configuration, skipping\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"fluent\" chart repository\n...Successfully got an update from the \"opensearch\" chart repository\n...Successfully got an update from the \"prometheus-community\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nsecret \"v4m-osd-tls-enabled\" deleted\nsecret/v4m-osd-tls-enabled created\nINFO Deploying OpenSearch Dashboards\nRelease \"v4m-osd\" has been upgraded. Happy Helming!\nNAME: v4m-osd\nLAST DEPLOYED: Thu Aug  4 10:37:11 2022\nNAMESPACE: logging\nSTATUS: deployed\nREVISION: 3\nTEST SUITE: None\nNOTES:\n1. Get the application URL by running these commands:\n  https://dashboards.viya4climaterisk.local/\nINFO OpenSearch Dashboards has been deployed\n\n\nsecret \"opensearch-cert-subjects\" deleted\nsecret/opensearch-cert-subjects created\nconfigmap \"run-securityadmin.sh\" deleted\nconfigmap/run-securityadmin.sh created\nconfigmap/run-securityadmin.sh labeled\n\"opensearch\" already exists with the same configuration, skipping\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"opensearch\" chart repository\n...Successfully got an update from the \"fluent\" chart repository\n...Successfully got an update from the \"prometheus-community\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nINFO Deploying OpenSearch\nRelease \"opensearch\" has been upgraded. Happy Helming!\nNAME: opensearch\nLAST DEPLOYED: Thu Aug  4 10:37:32 2022\nNAMESPACE: logging\nSTATUS: deployed\nREVISION: 3\nTEST SUITE: None\nNOTES:\nWatch all cluster members come up.\n  $ kubectl get pods --namespace=logging -l app.kubernetes.io/component=v4m-search -w\nINFO Waiting on OpenSearch pods to be Ready\npod/v4m-search-0 condition met\nINFO OpenSearch has been deployed\n\n\nINFO Deploying Elasticsearch metric exporter ...\n\"prometheus-community\" already exists with the same configuration, skipping\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"fluent\" chart repository\n...Successfully got an update from the \"opensearch\" chart repository\n...Successfully got an update from the \"prometheus-community\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nRelease \"es-exporter\" has been upgraded. Happy Helming!\nNAME: es-exporter\nLAST DEPLOYED: Thu Aug  4 10:39:37 2022\nNAMESPACE: logging\nSTATUS: deployed\nREVISION: 3\nTEST SUITE: None\nNOTES:\n1. Get the application URL by running these commands:\n  export POD_NAME=$(kubectl get pods --namespace logging -l \"app=v4m-es-exporter\" -o jsonpath=\"{.items[0].metadata.name}\")\n  echo \"Visit http://127.0.0.1:9108/metrics to use your application\"\n  kubectl port-forward $POD_NAME 9108:9108 --namespace logging\nINFO Elasticsearch metric exporter has been deployed\n\n\nINFO Loading Content into OpenSearch\nINFO The index management policy [viya_logs_idxmgmt_policy] already exist in OpenSearch; skipping load and using existing policy.\nINFO The index management policy [viya_ops_idxmgmt_policy] already exist in OpenSearch; skipping load and using existing policy.\n\n\nAccess controls created [Thursday, 04 August, 2022 10:39:47 AM PST]            \n\nWARN A user 'logadm' already exists; leaving that user as-is.  Review its definition in OpenSearch Dashboards and update it, or create another user, as needed.\nINFO Content has been loaded into OpenSearch\n\n\nINFO Configuring OpenSearch Dashboards...this may take a few minutes\nINFO Waiting for OpenSearch Dashboards pods to be ready (Thursday, 04 August, 2022 10:39:48 AM PST - timeout 10m)\npod/v4m-osd-55c8b9d5d7-jjzql condition met\n\nINFO Importing content in [logging/osd/common] to tenant space [cluster_admins]...\nINFO Imported content into tenant space [cluster_admins].\n\nINFO Importing content in [logging/osd/cluster_admins] to tenant space [cluster_admins]...\nINFO Imported content into tenant space [cluster_admins].\n\nINFO Importing content in [logging/osd/namespace] to tenant space [cluster_admins]...\nINFO Imported content into tenant space [cluster_admins].\n\nINFO Importing content in [logging/osd/tenant] to tenant space [cluster_admins]...\nINFO Imported content into tenant space [cluster_admins].\nINFO Configuring OpenSearch Dashboards has been completed\n\n\nINFO Deploying Fluent Bit ...\n\"fluent\" already exists with the same configuration, skipping\nconfigmap/fb-fluent-bit-config unchanged\nconfigmap \"fb-viya-parsers\" deleted\nconfigmap/fb-viya-parsers created\nconfigmap \"fb-env-vars\" deleted\nconfigmap/fb-env-vars created\nconfigmap/fb-env-vars labeled\npod \"v4m-fb-8bwjf\" deleted\npod \"v4m-fb-97kg2\" deleted\npod \"v4m-fb-dn7dx\" deleted\npod \"v4m-fb-jhk58\" deleted\npod \"v4m-fb-xlksf\" deleted\nRelease \"v4m-fb\" has been upgraded. Happy Helming!\nNAME: v4m-fb\nLAST DEPLOYED: Thu Aug  4 10:40:17 2022\nNAMESPACE: logging\nSTATUS: deployed\nREVISION: 3\nNOTES:\nGet Fluent Bit build information by running these commands:\n\nexport POD_NAME=$(kubectl get pods --namespace logging -l \"app.kubernetes.io/name=fluent-bit,app.kubernetes.io/instance=v4m-fb\" -o jsonpath=\"{.items[0].metadata.name}\")\nkubectl --namespace logging port-forward $POD_NAME 2020:2020\ncurl http://127.0.0.1:2020\nINFO Fluent Bit deployment completed\n\n\nINFO Updating Viya Monitoring for Kubernetes version information\nRelease \"v4m-logs\" has been upgraded. Happy Helming!\nNAME: v4m-logs\nLAST DEPLOYED: Thu Aug  4 10:40:21 2022\nNAMESPACE: logging\nSTATUS: deployed\nREVISION: 3\nTEST SUITE: None\nNOTES:\nViya Monitoring for Kubernetes 1.2.1 is installed\n\n**OpenSearch/OSD Access Controls**                                             \nAssign users the back-end role of [V4MCLUSTER_ADMIN_kibana_users] to           \ngrant them access to OpenSearch Dashboards and log messages from               \nALL tenants and ALL namespaces                                                 \n                                                                               \n**Accessing the monitoring applications**                                      \n                                                                               \nYou can access OpenSearch Dashboards via the following URL:                    \nhttps://dashboards.viya4climaterisk.local                                      \n                                                                               \nYou can access OpenSearch via the following URL:                               \nhttps://search.viya4climaterisk.local                                          \n                                                                               ",
  "stdout_lines": [
    "INFO User directory: /tmp/ansible._sw983lx",
    "INFO Helm client version: 3.9.2",
    "INFO Kubernetes client version: v1.22.12",
    "INFO Kubernetes server version: v1.22.11-eks-18ef993",
    "",
    "Deploying logging components to the [logging] namespace [Thursday, 04 August, 2022 10:37:08 AM PST]",
    "",
    "INFO Deploying Event Router ...",
    "serviceaccount/eventrouter unchanged",
    "clusterrole.rbac.authorization.k8s.io/eventrouter unchanged",
    "clusterrolebinding.rbac.authorization.k8s.io/eventrouter unchanged",
    "configmap/eventrouter-cm unchanged",
    "deployment.apps/eventrouter unchanged",
    "INFO Event Router has been deployed",
    "",
    "",
    "\"opensearch\" already exists with the same configuration, skipping",
    "Hang tight while we grab the latest from your chart repositories...",
    "...Successfully got an update from the \"fluent\" chart repository",
    "...Successfully got an update from the \"opensearch\" chart repository",
    "...Successfully got an update from the \"prometheus-community\" chart repository",
    "Update Complete. ⎈Happy Helming!⎈",
    "secret \"v4m-osd-tls-enabled\" deleted",
    "secret/v4m-osd-tls-enabled created",
    "INFO Deploying OpenSearch Dashboards",
    "Release \"v4m-osd\" has been upgraded. Happy Helming!",
    "NAME: v4m-osd",
    "LAST DEPLOYED: Thu Aug  4 10:37:11 2022",
    "NAMESPACE: logging",
    "STATUS: deployed",
    "REVISION: 3",
    "TEST SUITE: None",
    "NOTES:",
    "1. Get the application URL by running these commands:",
    "  https://dashboards.viya4climaterisk.local/",
    "INFO OpenSearch Dashboards has been deployed",
    "",
    "",
    "secret \"opensearch-cert-subjects\" deleted",
    "secret/opensearch-cert-subjects created",
    "configmap \"run-securityadmin.sh\" deleted",
    "configmap/run-securityadmin.sh created",
    "configmap/run-securityadmin.sh labeled",
    "\"opensearch\" already exists with the same configuration, skipping",
    "Hang tight while we grab the latest from your chart repositories...",
    "...Successfully got an update from the \"opensearch\" chart repository",
    "...Successfully got an update from the \"fluent\" chart repository",
    "...Successfully got an update from the \"prometheus-community\" chart repository",
    "Update Complete. ⎈Happy Helming!⎈",
    "INFO Deploying OpenSearch",
    "Release \"opensearch\" has been upgraded. Happy Helming!",
    "NAME: opensearch",
    "LAST DEPLOYED: Thu Aug  4 10:37:32 2022",
    "NAMESPACE: logging",
    "STATUS: deployed",
    "REVISION: 3",
    "TEST SUITE: None",
    "NOTES:",
    "Watch all cluster members come up.",
    "  $ kubectl get pods --namespace=logging -l app.kubernetes.io/component=v4m-search -w",
    "INFO Waiting on OpenSearch pods to be Ready",
    "pod/v4m-search-0 condition met",
    "INFO OpenSearch has been deployed",
    "",
    "",
    "INFO Deploying Elasticsearch metric exporter ...",
    "\"prometheus-community\" already exists with the same configuration, skipping",
    "Hang tight while we grab the latest from your chart repositories...",
    "...Successfully got an update from the \"fluent\" chart repository",
    "...Successfully got an update from the \"opensearch\" chart repository",
    "...Successfully got an update from the \"prometheus-community\" chart repository",
    "Update Complete. ⎈Happy Helming!⎈",
    "Release \"es-exporter\" has been upgraded. Happy Helming!",
    "NAME: es-exporter",
    "LAST DEPLOYED: Thu Aug  4 10:39:37 2022",
    "NAMESPACE: logging",
    "STATUS: deployed",
    "REVISION: 3",
    "TEST SUITE: None",
    "NOTES:",
    "1. Get the application URL by running these commands:",
    "  export POD_NAME=$(kubectl get pods --namespace logging -l \"app=v4m-es-exporter\" -o jsonpath=\"{.items[0].metadata.name}\")",
    "  echo \"Visit http://127.0.0.1:9108/metrics to use your application\"",
    "  kubectl port-forward $POD_NAME 9108:9108 --namespace logging",
    "INFO Elasticsearch metric exporter has been deployed",
    "",
    "",
    "INFO Loading Content into OpenSearch",
    "INFO The index management policy [viya_logs_idxmgmt_policy] already exist in OpenSearch; skipping load and using existing policy.",
    "INFO The index management policy [viya_ops_idxmgmt_policy] already exist in OpenSearch; skipping load and using existing policy.",
    "",
    "",
    "Access controls created [Thursday, 04 August, 2022 10:39:47 AM PST]            ",
    "",
    "WARN A user 'logadm' already exists; leaving that user as-is.  Review its definition in OpenSearch Dashboards and update it, or create another user, as needed.",
    "INFO Content has been loaded into OpenSearch",
    "",
    "",
    "INFO Configuring OpenSearch Dashboards...this may take a few minutes",
    "INFO Waiting for OpenSearch Dashboards pods to be ready (Thursday, 04 August, 2022 10:39:48 AM PST - timeout 10m)",
    "pod/v4m-osd-55c8b9d5d7-jjzql condition met",
    "",
    "INFO Importing content in [logging/osd/common] to tenant space [cluster_admins]...",
    "INFO Imported content into tenant space [cluster_admins].",
    "",
    "INFO Importing content in [logging/osd/cluster_admins] to tenant space [cluster_admins]...",
    "INFO Imported content into tenant space [cluster_admins].",
    "",
    "INFO Importing content in [logging/osd/namespace] to tenant space [cluster_admins]...",
    "INFO Imported content into tenant space [cluster_admins].",
    "",
    "INFO Importing content in [logging/osd/tenant] to tenant space [cluster_admins]...",
    "INFO Imported content into tenant space [cluster_admins].",
    "INFO Configuring OpenSearch Dashboards has been completed",
    "",
    "",
    "INFO Deploying Fluent Bit ...",
    "\"fluent\" already exists with the same configuration, skipping",
    "configmap/fb-fluent-bit-config unchanged",
    "configmap \"fb-viya-parsers\" deleted",
    "configmap/fb-viya-parsers created",
    "configmap \"fb-env-vars\" deleted",
    "configmap/fb-env-vars created",
    "configmap/fb-env-vars labeled",
    "pod \"v4m-fb-8bwjf\" deleted",
    "pod \"v4m-fb-97kg2\" deleted",
    "pod \"v4m-fb-dn7dx\" deleted",
    "pod \"v4m-fb-jhk58\" deleted",
    "pod \"v4m-fb-xlksf\" deleted",
    "Release \"v4m-fb\" has been upgraded. Happy Helming!",
    "NAME: v4m-fb",
    "LAST DEPLOYED: Thu Aug  4 10:40:17 2022",
    "NAMESPACE: logging",
    "STATUS: deployed",
    "REVISION: 3",
    "NOTES:",
    "Get Fluent Bit build information by running these commands:",
    "",
    "export POD_NAME=$(kubectl get pods --namespace logging -l \"app.kubernetes.io/name=fluent-bit,app.kubernetes.io/instance=v4m-fb\" -o jsonpath=\"{.items[0].metadata.name}\")",
    "kubectl --namespace logging port-forward $POD_NAME 2020:2020",
    "curl http://127.0.0.1:2020",
    "INFO Fluent Bit deployment completed",
    "",
    "",
    "INFO Updating Viya Monitoring for Kubernetes version information",
    "Release \"v4m-logs\" has been upgraded. Happy Helming!",
    "NAME: v4m-logs",
    "LAST DEPLOYED: Thu Aug  4 10:40:21 2022",
    "NAMESPACE: logging",
    "STATUS: deployed",
    "REVISION: 3",
    "TEST SUITE: None",
    "NOTES:",
    "Viya Monitoring for Kubernetes 1.2.1 is installed",
    "",
    "**OpenSearch/OSD Access Controls**                                             ",
    "Assign users the back-end role of [V4MCLUSTER_ADMIN_kibana_users] to           ",
    "grant them access to OpenSearch Dashboards and log messages from               ",
    "ALL tenants and ALL namespaces                                                 ",
    "                                                                               ",
    "**Accessing the monitoring applications**                                      ",
    "                                                                               ",
    "You can access OpenSearch Dashboards via the following URL:                    ",
    "https://dashboards.viya4climaterisk.local                                      ",
    "                                                                               ",
    "You can access OpenSearch via the following URL:                               ",
    "https://search.viya4climaterisk.local                                          ",
    "                                                                               "
  ]
}

**Comment by gsmith-sas** [comment]
@terencet3 Sorry you are running into a problem.  This is an odd issue: from the output you shared, it appears that the script completed and was able to deploy the log monitoring components.  

I noticed two things:

- It appears you are updating an existing deployment of the log monitoring components, rather than installing things for the first time on this cluster.  Is that correct?  Do you know what version of our log monitoring was deployed originally?

- The other thing I notice is that the last few messages the script writes out are missing.  Just after the OpenSearch URL, there should be a message indicating that the  URLs might be incorrect depending on your network configuration.  And, the last message should be something like "The deployment of logging components has completed" followed by a timestamp.

Have your tried re-running the task again (more than once)?  I'm wondering if there was some transient networking issue that occurred when this was being run.  It would be helpful to know if the problem is repeatable.  

Thanks,
Greg
p.s.  If you are a SAS employee, please reach out to me via internal e-mail.  It may make sense for me to access the environment directly.

**Comment by gsmith-sas** [comment]
I discussed this with @terencet3 off-line and he has decided to omit the monitoring solution from his cluster creation for now.
