### ISSUE TITLE
logging/bin/onboard.sh script won't create user for specific namespace able to download CSV reports

### ISSUE THREAD

**Issue by dougmanoel** [sassoftware/viya4-monitoring-kubernetes#398]
I tried to create a user following doc ([SAS Help Center: Controlling User Access](https://go.documentation.sas.com/doc/en/sasadmincdc/v_031/callogging/p1nee94eh0x1ymn1blz03g48jz2y.htm#p1b1d481588fgbn1oyauk68imlr8)) as shown below to limit that user on Viya k8s namespace (you will see it names as "tlaprod" in our case). However that user won’t be able to download CSV report due error "Insufficient permissions. Reach out to your OpenSearch Dashboards administrator".

I don’t see ‘logadm’ user a fit for our needs since this user can look logs from other k8s namespaces (not Viya only then) – that is why we need a read-only user. We call it that way to define it as a non-admin user. 

`
 

(⎈|TLA-prod:default)➜  bin git:(master) pwd

/home/domora/viya4/TLA/APP_SERVICE/viya4-monitoring-kubernetes/logging/bin

(⎈|TLA-prod:default)➜  bin git:(master)

(⎈|TLA-prod:default)➜  bin git:(master) kubectl config set-context --current --namespace=logging

(⎈|TLA-prod:logging)➜  bin git:(master) ✗ sudo chmod +x *

[sudo] password for domora:

(⎈|TLA-prod:logging)➜  bin git:(master) ✗

(⎈|TLA-prod:logging)➜  bin git:(master) ✗ ./onboard.sh --namespace tlaprod --user ro_test_user --password <removed>

INFO User directory: /home/domora/viya4/TLA/APP_SERVICE/viya4-monitoring-kubernetes

INFO Helm client version: 3.8.2

INFO Kubernetes client version: v1.23.4

INFO Kubernetes server version: v1.22.6

INFO Loading user environment file: /home/domora/viya4/TLA/APP_SERVICE/viya4-monitoring-kubernetes/logging/user.env

 

Onboarding namespace [tlaprod] [Thu Sep  1 12:28:15 -03 2022]

INFO OpenSearch Dashboards tenant space [tlaprod] created. [201]

 

INFO Importing content in [logging/osd/common] to tenant space [tlaprod]...

INFO Imported content into tenant space [tlaprod].

 

INFO Importing content in [logging/osd/namespace] to tenant space [tlaprod]...

INFO Imported content into tenant space [tlaprod].

 

Creating access controls for namespace [tlaprod] [Thu Sep  1 12:28:55 -03 2022]

INFO Security role [search_index_tlaprod] created. [201]

INFO Security rolemapping created between [search_index_tlaprod] and backend-role(s) [tlaprod_kibana_users]. [201]

INFO Security rolemapping created between [v4m_grafana_dsuser] and backend-role(s) [tlaprod_grafana_dsusers]. [200]

INFO Security rolemapping created between [search_index_tlaprod] and backend-role(s) [tlaprod_grafana_dsusers]. [200]

INFO Security role [tenant_tlaprod] created. [201]

INFO Security rolemapping created between [tenant_tlaprod] and backend-role(s) [tlaprod_kibana_users]. [201]

INFO Security rolemapping created between [v4m_kibana_user] and backend-role(s) [tlaprod_kibana_users]. [200]

Access controls created [Thu Sep  1 12:29:12 -03 2022]

 

 

INFO Attempting to create user [ro_test_user] and grant them access to log messages from namespace [tlaprod] [Thu Sep  1 12:29:15 -03 2022]

INFO User [ro_test_user] created. [201]

User [ro_test_user] added to internal user database [Thu Sep  1 12:29:18 -03 2022]

 

==================================================================

 

The OpenSearch Dashboards tenant space [tlaprod] was created.

 

Assign users the back-end role of [tlaprod_kibana_users] to

grant them access to OpenSearch Dashboards and log messages from

ONLY the [tlaprod] namespace.

 

User [ro_test_user] added to internal user database.

 

==================================================================

 

Successfully onboarded namespace [tlaprod] [Thu Sep  1 12:29:18 -03 2022]

(⎈|TLA-prod:logging)➜  bin git:(master) ✗`

![error_CSV_reports](https://user-images.githubusercontent.com/92990713/188730935-2352d68e-cd1d-4950-9132-703de439d1be.png)

**Comment by dougmanoel** [comment]
Please note any team member from the group I am in may be involved to answer/clarify this issue. So please reply here for any information needed from us.

**Comment by cumcke** [comment]
Hey Doug,

I started looking into the issue that you're reporting and I am able to recreate the error that you are seeing.  I onboarded an "acme" tenant in my VIYA_NS namespace to Opensearch using the **onboard.sh** script and created a user called **acme_admin** ... after making a report, I did see the same error and found the matching log in the container logs.

{"type":"log","@timestamp":"2022-09-09T16:15:11Z","tags":["error","opensearch","data"],"pid":1,"message":"[security_exception]: no permissions for [indices:data/read/get] and User [name=acme_admin, backend_roles=[<VIYA_NS>_acme_kibana_users], requestedTenant=null]"}

It seems that the new user that you are creating needs (at least) the **indices:data/read/get** permission.  I'm working through the interface to determine what else would need to be added if you do not want to use the **admin** or **logadm** users for this task.

**Comment by gsmith-sas** [comment]
@dougmanoel The experimental getlogs.sh script allows you to specify the user and password, so it should be possible to run the script using the limited-access user you created.  But if your users cannot access the command line and script, that won't help you.

The ERROR message generated when a user requests a CSV indicates that the permission "indices:data/read/get" is missing for this user.  However, even after granting this additional permission the request to create a CSV fails.  After granting this permission, the ERROR messages indicate that a new/different permission, "indices:monitor/settings/get", is missing. Unfortunately, even after explicitly granting this 2nd additional permission to the user, the request fails. Strangely, the ERROR message indicates that the (same) "indices:monitor/settings/get", is (still) missing.  So resolving this will take some further research.  I cannot provide an estimated timeline for resolving this issue at this time.

**Comment by gsmith-sas** [comment]
@dougmanoel We have just pushed a fix for this problem to our `main` branch.  It will be part of our next release, version 1.2.8, due out early next week.  As always, once the new version has been released, the `stable` branch will be updated to deploy that version.
