### ISSUE TITLE
v4m node exporter / kubelet service tries to connect to Connect Spawner every second.

### ISSUE THREAD

**Issue by frayos** [sassoftware/viya4-monitoring-kubernetes#405]
Hello,
V4M Release 1.2.x
SAS Release : 2022.1 LTS
SAS Cloud Reference : YNV-346
SAS TS Reference : 7613656931

One of our customer have "exloding" SAS Connect log because v4m-kubelete / v4m-node-exporter tries to connect to port 17551
This is a LoadBalancer type service for SAS Connect Spawner 

Is there a way to avoid all those connections ? 
In parallel I'm asking SAS TS on how to remove it with the logconfig.xml

Thanks ! 
Younes / SAS Cloud Admin

Log excerpt : 

> 2022-09-22T18:01:15,362 INFO  [00094349] :sas - Client connection 0x7fd099571820 accepted from 10-227-132-70.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.70) on port 17551.
> 2022-09-22T18:01:16,708 INFO  [00094350] :sas - Client connection 0x7fd0994440a0 accepted from 10-227-132-75.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.75) on port 17551.
> 2022-09-22T18:01:16,802 INFO  [00094351] :sas - Client connection 0x7fd099444c80 accepted from 10-227-132-72.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.72) on port 17551.
> 2022-09-22T18:01:17,527 INFO  [00094352] :sas - Client connection 0x7fd099445f80 accepted from 10-227-132-76.v4m-node-exporter.monitoring.svc.cluster.local (10.227.132.76) on port 17551.
> 2022-09-22T18:01:17,611 INFO  [00094353] :sas - Client connection 0x7fd099446b60 accepted from 10-227-132-73.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.73) on port 17551.
> 2022-09-22T18:01:17,617 INFO  [00094354] :sas - Client connection 0x7fd09956ca60 accepted from 10-227-132-71.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.71) on port 17551.
> 2022-09-22T18:01:20,425 INFO  [00094355] :sas - Client connection 0x7fd09956fcc0 accepted from 10-227-132-69.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.69) on port 17551.
> 2022-09-22T18:01:21,374 INFO  [00094356] :sas - Client connection 0x7fd0995708a0 accepted from 10-227-132-70.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.70) on port 17551.
> 2022-09-22T18:01:22,725 INFO  [00094358] :sas - Client connection 0x7fd0994680a0 accepted from 10-227-132-75.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.75) on port 17551.
> 2022-09-22T18:01:22,808 INFO  [00094359] :sas - Client connection 0x7fd099571820 accepted from 10-227-132-72.v4m-node-exporter.monitoring.svc.cluster.local (10.227.132.72) on port 17551.
> 2022-09-22T18:01:23,536 INFO  [00094360] :sas - Client connection 0x7fd09956d640 accepted from 10-227-132-76.v4m-node-exporter.monitoring.svc.cluster.local (10.227.132.76) on port 17551.
> 2022-09-22T18:01:23,614 INFO  [00094361] :sas - Client connection 0x7fd0994440a0 accepted from 10-227-132-73.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.73) on port 17551.
> 2022-09-22T18:01:23,620 INFO  [00094362] :sas - Client connection 0x7fd099444c80 accepted from 10-227-132-71.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.71) on port 17551.
> 2022-09-22T18:01:26,431 INFO  [00094363] :sas - Client connection 0x7fd099445f80 accepted from 10-227-132-69.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.69) on port 17551.
> 2022-09-22T18:01:27,380 INFO  [00094364] :sas - Client connection 0x7fd099446b60 accepted from 10-227-132-70.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.70) on port 17551.
> 2022-09-22T18:01:28,733 INFO  [00094365] :sas - Client connection 0x7fd09956fcc0 accepted from 10-227-132-75.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.75) on port 17551.
> 2022-09-22T18:01:28,815 INFO  [00094366] :sas - Client connection 0x7fd0995708a0 accepted from 10-227-132-72.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.72) on port 17551.
> 2022-09-22T18:01:29,555 INFO  [00094367] :sas - Client connection 0x7fd0994680a0 accepted from 10-227-132-76.v4m-node-exporter.monitoring.svc.cluster.local (10.227.132.76) on port 17551.
> 2022-09-22T18:01:29,617 INFO  [00094368] :sas - Client connection 0x7fd099571820 accepted from 10-227-132-73.v4m-node-exporter.monitoring.svc.cluster.local (10.227.132.73) on port 17551.
> 2022-09-22T18:01:29,627 INFO  [00094369] :sas - Client connection 0x7fd09956ca60 accepted from 10-227-132-71.v4m-kubelet.kube-system.svc.cluster.local (10.227.132.71) on port 17551

**Comment by gsmith-sas** [comment]
It is my understanding that this issue turned out to be a a SAS/Connect issue.  Therefore, I am closing this issue.

**Comment by frayos** [comment]
Hello,
SAS Connect did crash because of the volume of the log yes, because logconfig.xml was wrong yes
but
NO
this is not a SAS Connect issue

Question remains : 
Is there a way to avoid all those connections ?

To be noted this also happens on CAS
