### ISSUE TITLE
Deploying the monitoring component - errors with grafana container

### ISSUE THREAD

**Issue by HaraldSeifert** [sassoftware/viya4-monitoring-kubernetes#462]
Trying to deploy the monitoring component I got an error: 
This is what happens:
NOTE: Deploy SAS Viya Kubernetes Monitoring
INFO OpenShift client version: 4.10.0
INFO OpenShift server version: 4.10.50
INFO User directory: /opt/sas/viya4/deploy_sasvyw/sasvy4w/viya-monitoring-kubernetes-1.2.8
INFO Helm client version: 3.9.3
INFO Kubernetes client version: v1.22.0
INFO Kubernetes server version: v1.23.12+8a6bfe4

namespace/monitoring created
Deploying monitoring to the [monitoring] namespace...
"grafana" has been added to your repositories
INFO Updating helm repositories...
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "grafana" chart repository
Update Complete. ⎈Happy Helming!⎈
INFO Enabling Grafana to access OpenShift Prometheus instances...
INFO Creating Grafana serviceAccount...
serviceaccount/grafana-serviceaccount created
clusterrole.rbac.authorization.k8s.io/cluster-monitoring-view added: "grafana-serviceaccount"
INFO Deploying monitoring components for OpenShift...
INFO Deploying Grafana...
Release "v4m-grafana" does not exist. Installing it now.
W0213 16:51:16.816585 2902971 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0213 16:51:16.898894 2902971 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ 

Der install endet mit dem Event: 
P[v4m-grafana-6d5d98cd88-rj68p](https://console-openshift-console.apps.lan-tpc-001.ocp.lan.huk-coburg.de/k8s/ns/monitoring/pods/v4m-grafana-6d5d98cd88-rj68p)NamespaceNS[monitoring](https://console-openshift-console.apps.lan-tpc-001.ocp.lan.huk-coburg.de/k8s/cluster/namespaces/monitoring)
Just now
Generated from kubelet on [scp00a14.ocp.lan.huk-coburg.de](https://console-openshift-console.apps.lan-tpc-001.ocp.lan.huk-coburg.de/k8s/cluster/nodes/scp00a14.ocp.lan.huk-coburg.de)10 times in the last 1 minute
Failed to apply default image tag ":9.2.3": couldn't parse image reference ":9.2.3": invalid reference format

$ helm repo list
NAME    URL
grafana https://nexus.lan.huk-coburg.de/repository/helm-grafana 

In the user.env I have defined the route to the existing grafana environment. 
OPENSHIFT_ROUTE_HOST_GRAFANA=grafana-openshift-monitoring.apps.lan-tpc-001.ocp.lan.huk-coburg.de

Guessing 9.2.3 is the grafana realease, but I found only tags in the yaml files; but no section, where I can specify for example a nexus repository with grafana (There I found a grafana 9.3.1 tag) 
Anything known ? How can I proceed.

**Comment by HaraldSeifert** [comment]
Switching to 1.2.9 works better. The containers start, but I have no data in the grafana dashboards.

**Comment by cumcke** [comment]
Hi @HaraldSeifert ,

Just for clarification, are you saying that, right after successfully deploying Viya 4 Monitoring for Kubernetes version 1.2.9, you were unable to see data on some or all of the Grafana dashboards?

If this is the case, can you tell me which dashboard(s) you are looking at are missing data?

**Comment by HaraldSeifert** [comment]
Hi, all dashboards are without data. Regards


Harald Seifert
Abteilung Informatik - Betrieb

HUK-COBURG
Bahnhofsplatz
96444 Coburg
Telefon:        09561 96-44621
Telefax:        09561 96-44963
E-Mail: ***@***.***
Internet:       www.huk.de
________________________________
HUK-COBURG Haftpflicht-Unterstützungs-Kasse kraftfahrender Beamter Deutschlands a. G. in Coburg
Reg.-Gericht Coburg HRB 100; St.-Nr. 9212/101/00021
Sitz der Gesellschaft: Bahnhofsplatz, 96444 Coburg
Vorsitzender des Aufsichtsrats: Prof. Dr. Heinrich R. Schradin.
Vorstand: Klaus-Jürgen Heitmann (Sprecher), Stefan Gronbach, Dr. Hans Olav Herøy, Dr. Helen Reck, Dr. Jörg Rheinländer, Thomas Sehn, Daniel Thomas.
________________________________
Diese Nachricht enthält vertrauliche und/oder rechtlich geschützte Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese Nachricht irrtümlich erhalten haben,
informieren Sie bitte sofort den Absender und vernichten Sie diese Nachricht.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Nachricht ist nicht gestattet.

This information may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this information in error) please notify the
sender immediately and destroy this information.
Any unauthorized copying, disclosure or distribution of the material in this information is strictly forbidden.
________________________________
Von: cumcke ***@***.***>
Gesendet: Freitag, 17. Februar 2023 17:38
An: sassoftware/viya4-monitoring-kubernetes ***@***.***>
Cc: Seifert, Harald ***@***.***>; Mention ***@***.***>
Betreff: Re: [sassoftware/viya4-monitoring-kubernetes] Deploying the monitoring component - errors with grafana container (Issue #462)


Hi @HaraldSeifert<https://github.com/HaraldSeifert> ,

Just for clarification, are you saying that, right after successfully deploying Viya 4 Monitoring for Kubernetes version 1.2.9, you were unable to see data on some or all of the Grafana dashboards?

If this is the case, can you tell me which dashboard(s) you are looking at are missing data?

**Comment by gsmith-sas** [comment]
@HaraldSeifert I am closing this issue since it is is a year old.  Please open a new issue if you continue to have trouble deploying Grafana.  

Please also review the information in the [OpenShift.md (readme) file in the monitoring sub-directory of our repo](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/monitoring/OpenShift.md#azure-red-hat-openshift-experimental); specifically the information about the need to set the `enableUserWorkload` key in the `cluster-monitoring-config` configMap.  While that section mentions Azure Red Hat OpenShift, I believe we have occasionally seen the same thing on non-Azure OpenShift and the symptoms you describe (Grafana up but no data available) match what I would expect if user workload monitoring has not been enabled.
