### ISSUE TITLE
Grafana dashboard - SAS CAS overview

### ISSUE THREAD

**Issue by alessiotoma** [sassoftware/viya4-monitoring-kubernetes#47]
The dashboard SAS CAS Overview reports memory usage for the CAS server, which is very different than reported by the OS or kubectl top.

The Grafana dashboard reports about 22GB memory, while kubectl reports about 1GB. It may be that the stats are exported from the 'sas-cas-control' pod which is not on the same node as the 'sas-cas-server-default-controller' pod.

**Comment by alessiotoma** [comment]
The following message is also prevalent in the dashboard:

"found duplicate series for the match group {cas_server=\"cas-shared-default\", namespace=\"viya2020\"} on the right hand-side of the operation: [{__name__=\"cas_os_info\", cas_server=\"cas-shared-default\", container=\"cas\", endpoint=\"http\", instance=\"10.244.34.5:8777\", job=\"sas-cas-server-default-http\", name=\"Linux\", namespace=\"viya2020\", pod=\"sas-cas-server-default-controller\", release=\"5.4.0-1031-azure\", service=\"sas-cas-server-default-http\", system=\"X86_64 Linux\", version=\"#32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020\"}, {__name__=\"cas_os_info\", cas_server=\"cas-shared-default\", container=\"cas\", endpoint=\"http\", instance=\"10.244.34.5:8777\", job=\"sas-cas-server-default-client\", name=\"Linux\", namespace=\"viya2020\", pod=\"sas-cas-server-default-controller\", release=\"5.4.0-1031-azure\", service=\"sas-cas-server-default-client\", system=\"X86_64 Linux\", version=\"#32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020\"}];many-to-many matching not allowed: matching labels must be unique on one side"

**Comment by BryanEllington** [comment]
The memory reported on the SAS CAS Overview dashboard is the 'cas_node_mem_size_bytes' metric reported by the CAS server. The graph currently only shows 'physical' memory so it does not sum up with cas_node_mem_size_bytes metrics with the 'swap' or 'virtual' labels.

Would you suggest the memory graph include all 3 (physical, virtual, swap), add a stacked bar graph for current memory usage by node (each stacked by physical, virtual, swap), or do you have other ideas?
