### ISSUE TITLE
SMTP / email notifications configuration question

### ISSUE THREAD

**Issue by edward2a** [sassoftware/viya4-monitoring-kubernetes#496]
Hi SAS team!

By any chance, do you have any documentation or indications on how to configure email alerting / SMTP with this viya4-monitoring setup?

Or shall I assume this is to be done separately?

Thank you,
Ed

**Comment by gsmith-sas** [comment]
Two of the components deployed as part of this project can handle alerting (including sending notifications via e-mails or other channels): Prometheus Alertmanager and Grafana.  However, our deployment scripts do not currently automate the notification integration/configuration.  But one of our colleagues has written blog posts (available in the SAS Communities Library Forums) that discuss alerting including how to configure Alertmanager and Grafana.  The most recent one, [Comparing Alerting Capabilities of Alertmanager with Grafana](https://communities.sas.com/t5/SAS-Communities-Library/Comparing-Alerting-Capabilities-of-Alertmanager-with-Grafana/ta-p/925286), is probably a good starting point.  It also includes links to the other posts that cover the configuration details (see the box labeled **_Related Topics_** on the right side of page).

You can also refer to the [Prometheus Alertmanager documentation ](https://prometheus.io/docs/alerting/latest/configuration/) and/or the [Grafana documentation](https://grafana.com/docs/grafana/v11.1/alerting/) for more complete details about configuring these applications.
