### ISSUE TITLE
Respect TLS verification 

### ISSUE THREAD

**Issue by Carus11** [sassoftware/viya4-monitoring-kubernetes#507]
the project has several --insecure-skip-tls-verification flags where it disregards any issues with verifying the identity of the remote system.
This does not align with the security policies of SAS

For example:
https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/662762021e0a9d5bc1645692ba67067ac99eaccc/monitoring/bin/deploy_monitoring_cluster.sh#L80

**Comment by gsmith-sas** [comment]
We removed the instances of kubectl calls with the --insecure-skip-tls-verify from our code soon after this issue was opened.  We have also added an item to our backlog to look into other places in our code where we may be skipping TLS certificate validation and how we can eliminate them.
