### ISSUE TITLE
 how to send email 

### ISSUE THREAD

**Issue by sarnakamura** [sassoftware/viya4-monitoring-kubernetes#556]
We would like to send emails from Alert Manager.
Normally, all you need to do is change the receiver in alertmanager.yaml.
However, since this project is a container, the file to be changed cannot be found.
Please tell me how to send email from alertmanager.

**Comment by gsmith-sas** [comment]
@sarnakamura One of our colleagues, Ajmal Farzam, wrote a blog post about how to configure Alertmanager to send out e-mail.  It is available on the SAS Communities site; please take a look at his titled [A First Look at Alerting in SAS Viya]( https://communities.sas.com/t5/SAS-Communities-Library/A-first-look-at-alerting-in-SAS-Viya/ta-p/747245).
