### ISSUE TITLE
unable to load openshift/oauth-proxy 

### ISSUE THREAD

**Issue by LainerSAS** [sassoftware/viya4-monitoring-kubernetes#602]
After upgrade Openshift 4.9+, Oauth-proxy unable to load OpenShift configuration: unable to retrieve authentication information for tokens: the server could not find the requested resource

https://access.redhat.com/solutions/6999861

Root Cause
Outdated oauth-proxy image from Dockerhub which still attempts to do v1beta1 TokenReviews which will be no longer available in Openshift 4.9+(Kubernetes 1.22+).

The openshift/oauth-proxy:latest image from the dockerhub has not been updated for over 4 years.

openshift/oauth-proxy:latest on Dockerhub:https://hub.docker.com/r/openshift/oauth-proxy/tags

Solution:
make sure using registry.redhat.io/openshift4/ose-oauth-proxy instead of openshift/oauth-proxy:latest

Edit Deployment of v4m-grafana Project.
Change Image Name: 
OLD:  openshift/oauth-proxy:latest
NEW: registry.redhat.io/openshift4/ose-oauth-proxy:latest

![2024-01-15_001](https://github.com/sassoftware/viya4-monitoring-kubernetes/assets/156697451/5295002d-050e-4de3-bffe-3bc0584da6b1)

**Comment by gsmith-sas** [comment]
Thank you @LainerSAS for reporting this issue...and for providing information about fixing it.  We will investigate things a bit further, determine how we want to proceed and package up a fix over the next few weeks.  

In the meantime, in addition to the work-around you describe (i.e. editing the deployment after deployment), I believe you can also provide the new image name in the monitoring/openshift/grafana-proxy-patch-path.yaml or the monitoring/openshift/grafana-proxy-patch-host.yaml files (depending on how you are making Grafana available) _before_ running the monitoring/bin/deploy_monitoring_openshift.sh script.  I should stress that this would only be a temporary fix as we generally recommend that users do not modify the files in the repository directly.  Instead, users should customize their configuration by adding/editing the appropriate files in their USER_DIR directory instead.  However, in this particular case, I suspect doing so would be cumbersome.  Once we've completed our work, this temporary fix shouldn't be necessary.

Thank you again for reporting the problem.  We will update this issue as we complete our work.

**Comment by gsmith-sas** [comment]
@LainerSAS We've pushed a change that corrects this issue.  This change is available now on our 'main' branch and will be available on our `stable` branch as part of our 1.2.22 release due out next week.  We generally recommend users pull from the 'stable' branch (generally updated monthly) unless they have a compelling reason to use our 'main' branch (which is our active development branch and updated much more frequently).  Thank you for reporting this issue.
