### ISSUE TITLE
Typo in 1.0.3 version of viya4-monitoring-kubernetes/samples/tls/monitoring/user.env file

### ISSUE THREAD

**Issue by Bridget-Kelly** [sassoftware/viya4-monitoring-kubernetes#64]
Last week I was deploying the 1.0.3 version of the monitoring components and noticed what I believe is a typo in the viya4-monitoring-kubernetes/samples/tls/monitoring/user.env file. 

It says TLS_ENABLED which I believe is incorrect, and it should be TLS_ENABLE. 

I didn't realize this was wrong at first and I copied that sample file over to my USER_DIR directory (as per the instructions) and didn't change that variable. I did the rest of the steps and the deployment didn't report any errors, but I got HTTP 502 errors when trying to access my grafana and prometheus endpoints. When I eventually realized it should be TLS_ENABLE, I re-did the monitoring deployment exactly as I did before (but just with the correct environment variable this time in that user.env file) and it worked. 

This does seem to be fixed in that same file on the master branch, so perhaps this typo has already been noticed. But I did want to report it here because the 'Perform Pre-Deployment Tasks' steps do explicitly say to grab the latest release from the Releases page, and as of right now that is 1.0.3. So if others are following these instructions using the 1.0.3 release and using TLS, they might run into problems like I did if they don't realize the variable in the sample TLS user.env file is wrong. 

1.0.3 version I was using shows TLS_ENABLED: 
https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/1.0.3/samples/tls/monitoring/user.env 

master version shows TLS_ENABLE: 
https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/master/samples/tls/monitoring/user.env

**Comment by BryanEllington** [comment]
Thanks for the report. As you noted, this issue has been fixed. In fact, the TLS sample and several README files have been updated to clarify TLS support and the deployment customization process in general. These changes are in master and will be available in the upcoming 1.0.4 release next week.

**Comment by Bridget-Kelly** [comment]
Thanks for the reply Bryan! I'll keep an eye out for the 1.0.4 release next week.
