### ISSUE TITLE
Deploy Viya Monitoring for Kubernetes with GitOps such as ArgoCD

### ISSUE THREAD

**Issue by jan-ehlers** [sassoftware/viya4-monitoring-kubernetes#696]
Many OpenShift administrators prefer to have software deployed through their ArgoCD GitOps framework, where ArgoCD automatically applies yaml files and helmcharts and keeps Kubernetes etcd state in sync with the configuration defined in a git repository. The aproach is declarative and does not fit well with running shell scripts.

On a project I am working on we are close to have this working for SAS Viya deployment (based on site.yaml), but it seems like an immense amount of work to get this working for an air gap deployment of Viya Monitoring for Kubernetes on OpenShift. SAS documentation refers to advanced shell scripts such as [https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/main/monitoring/bin/deploy_monitoring_openshift.sh] which we do not want to translate ourselves into declarative yaml and helmcharts etc. as part of the project.

Does SAS support a declarative deployment method with GitOps for Viya Monitoring for Kubernetes, air gapped on OpenShift? If so, do we have a proven method and description of how to do this? Ideally with ArgoCD.

This type of automation could potentially also make disaster recovery faster, and less error prone.

**Comment by gsmith-sas** [comment]
@jan-ehlers This project currently only offers a script-based deployment process and, at this time, we have no plans to support a declarative deployment mechanism such as ArgoCD.  However, I will make sure our Product Manager (responsible for identifying product requirements and shaping our project roadmap) is aware of your request.

  I would also like to point out that our current deployment process can be integrated into a GitObs framework.  All of the user customizations for our project are controlled by either environment variables or Helm user-values yaml files.  The environment variables can be defined in the user.env files located in a customizations directory identified by the environment variable $USER_DIR.  The customized user-values yaml files are also pulled from this same USER_DIR directory.  Placing this USER_DIR directory (and it contents) under a source control system like git ensures that any changes are tracked.  While this approach, by itself, does not provide automatic redeployment when the files are changed, there are additional mechanisms, such as GitHub actions, that could be introduced that could handle automatic redeployment.

Additional information on the customization process (including the structure and contents of the USER_DIR directory) are included in the [Pre-Deployment](https://go.documentation.sas.com/doc/en/obsrvcdc/v_003/obsrvdply/n1ajbblsxpcgl5n11t13wgtd4d7c.htm) section of our [documentation](https://go.documentation.sas.com/doc/en/obsrvcdc/v_003/obsrvdply/n0bzfdp3bn6p4vn1lj9pm2hy8t0q.htm).
